"""Orchestrate mission workflow state with the existing evidence ledger."""

from __future__ import annotations

try:
    from ..mission_orchestrator import record_module_result
    from ..mission_schema import save_mission
    from .stage_definitions import get_stage_definition
    from .workflow_state import (
        create_initial_workflow_state,
        mark_stage_completed_external,
        skip_stage,
        start_workflow_from_stage,
        update_stage_status,
    )
except ImportError:  # pragma: no cover - supports direct app/ path imports.
    from mission_orchestrator import record_module_result
    from mission_schema import save_mission
    from workflow.stage_definitions import get_stage_definition
    from workflow.workflow_state import (
        create_initial_workflow_state,
        mark_stage_completed_external,
        skip_stage,
        start_workflow_from_stage,
        update_stage_status,
    )


DIRECT_LOCAL_RECON_BOUNDARIES = [
    "This mission starts from local RGB imagery without verified global mapping context.",
    "Local detection results cannot be treated as georeferenced rescue targets unless map registration is provided.",
    "Image-level target detection is decision-support evidence and requires human review.",
]

EXTERNAL_MAP_BOUNDARY = (
    "The external map was imported by the user; the system does not claim it was generated by AeroRescue-AI."
)


def _append_truthfulness_boundaries(mission, boundaries):
    mission.setdefault("truthfulness_boundaries", [])
    for boundary in boundaries:
        if boundary not in mission["truthfulness_boundaries"]:
            mission["truthfulness_boundaries"].append(boundary)
    return mission


def initialize_rescue_workflow(mission):
    """Attach an initial rescue workflow state unless the mission already has one."""
    if mission.get("workflow_state"):
        return mission
    mission["workflow_state"] = create_initial_workflow_state()
    return mission


def record_stage_output(
    mission,
    mission_dir,
    stage_key,
    output_ref="",
    result_type="",
    source_type="rule_based",
    confidence=None,
    score=None,
    truthfulness_note=None,
    limitation=None,
    human_review_required=True,
):
    """Record a completed workflow stage output as mission evidence."""
    mission = initialize_rescue_workflow(mission)
    stage_definition = get_stage_definition(stage_key)
    truthfulness_note = truthfulness_note or stage_definition["truthfulness_boundary"]
    limitation = limitation or stage_definition["truthfulness_boundary"]

    entry = record_module_result(
        mission,
        mission_dir,
        module=f"workflow:{stage_key}",
        input_ref=stage_key,
        output_ref=output_ref,
        result_type=result_type,
        confidence=confidence,
        score=score,
        source_type=source_type,
        truthfulness_note=truthfulness_note,
        limitation=limitation,
        human_review_required=human_review_required,
    )
    mission["workflow_state"] = update_stage_status(
        mission.get("workflow_state"),
        stage_key,
        "completed",
        output_ref=output_ref,
        result_type=result_type,
        evidence_id=entry["evidence_id"],
    )
    save_mission(mission, mission_dir)
    return entry


def fail_stage(mission, mission_dir, stage_key, error):
    """Mark a workflow stage as failed and persist mission.json."""
    mission = initialize_rescue_workflow(mission)
    mission["workflow_state"] = update_stage_status(
        mission.get("workflow_state"),
        stage_key,
        "failed",
        error=error,
    )
    save_mission(mission, mission_dir)
    return mission


def initialize_direct_local_recon_workflow(
    mission,
    local_rgb_images=None,
    manual_area_id="A",
    reason="User provided local RGB imagery and requested direct target detection.",
):
    """Initialize a mission that starts directly from S4 local RGB reconnaissance."""
    mission = initialize_rescue_workflow(mission)
    mission["workflow_state"] = start_workflow_from_stage(
        mission.get("workflow_state"),
        "local_recon",
        skipped_reason=reason,
    )
    mission["workflow_state"] = update_stage_status(
        mission.get("workflow_state"),
        "area_tasking",
        "manual_required",
        result_type="manual_area_tasking",
    )
    mission["workflow_state"]["stages"]["area_tasking"]["manual_area_id"] = str(manual_area_id or "A")
    mission["workflow_state"]["stages"]["area_tasking"][
        "truthfulness_note"
    ] = "Manual area tasking does not imply confirmed disaster severity."

    files = local_rgb_images or []
    if not isinstance(files, (list, tuple)):
        files = [files]
    mission["workflow_mode"] = "direct_local_recon"
    mission["global_context_available"] = False
    mission["macro_context_available"] = False
    mission["area_tasking_source"] = "manual"
    mission["manual_area_id"] = str(manual_area_id or "A")
    mission["direct_local_rgb_image_count"] = len([item for item in files if item])
    _append_truthfulness_boundaries(mission, DIRECT_LOCAL_RECON_BOUNDARIES)
    return mission


def initialize_external_map_workflow(
    mission,
    external_map_path,
    map_source_note="User-provided external map.",
):
    """Initialize a mission with S1 supplied by an external/user-provided map."""
    mission = initialize_rescue_workflow(mission)
    mission["workflow_state"] = mark_stage_completed_external(
        mission.get("workflow_state"),
        "global_mapping",
        output_ref=external_map_path,
        result_type="external_map_import",
        note=map_source_note,
    )
    mission["workflow_mode"] = "external_map_import"
    mission["global_context_available"] = True
    mission["macro_context_available"] = False
    _append_truthfulness_boundaries(mission, [EXTERNAL_MAP_BOUNDARY])
    return mission


def record_external_stage_artifact(
    mission,
    mission_dir,
    stage_key,
    artifact_path,
    result_type="external_import",
    note="",
):
    """Record a user/external artifact in Evidence Ledger and workflow state."""
    mission = initialize_rescue_workflow(mission)
    stage_definition = get_stage_definition(stage_key)
    truthfulness_note = note or stage_definition["truthfulness_boundary"]
    entry = record_module_result(
        mission,
        mission_dir,
        module=f"workflow:{stage_key}",
        input_ref=stage_key,
        output_ref=artifact_path,
        result_type=result_type,
        source_type="external_import",
        truthfulness_note=truthfulness_note,
        limitation=truthfulness_note,
        human_review_required=True,
    )
    mission["workflow_state"] = mark_stage_completed_external(
        mission.get("workflow_state"),
        stage_key,
        output_ref=artifact_path,
        result_type=result_type,
        evidence_id=entry["evidence_id"],
        note=truthfulness_note,
    )
    save_mission(mission, mission_dir)
    return entry
