name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install huggingface_hub ultralytics gradio opencv-python-headless

      - name: Push only app folder to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          set -e
          git config --global user.email "m.carolina.soares1@gmail.com"
          git config --global user.name "mariacarolinass"

          # Clona o Space com autenticação usando o token na URL
          git clone https://user:$HF_TOKEN@huggingface.co/spaces/carolinasoares/urban-disaster-monitor-v2 hf_space

          # Limpa conteúdo antigo
          rm -rf hf_space/*

          # Copia apenas a pasta app
          cp -r app/* hf_space/

          cd hf_space
          git add .
          git commit -m "Update from GitHub" || echo "Nada para commitar"
          git push
